force-app/main/default/objects/Activities__c/Activities__c.object-meta.xml
<CustomObject>
    <label>Activities</label>
    <nameField>
        <displayFormat>ACT-{000}</displayFormat>
        <label>Activity #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activities__c/fields/Activity_Source__c.field-meta.xml
<CustomField>
    <fullName>Activity_Source__c</fullName>
    <label>Activity Source</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activities__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activities__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>n/a</fullName>
            </value>
            <value>
                <fullName>1-ASAP</fullName>
            </value>
            <value>
                <fullName>2-High</fullName>
            </value>
            <value>
                <fullName>3-Medium</fullName>
            </value>
            <value>
                <fullName>4-Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activities__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New Fax Required</fullName>
            </value>
            <value>
                <fullName>Pending POI Document</fullName>
            </value>
            <value>
                <fullName>SLN Validated</fullName>
            </value>
            <value>
                <fullName>n/a</fullName>
                <isActive>false</isActive>
                <label>n/a</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activities__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Call - Inbound</fullName>
            </value>
            <value>
                <fullName>Call - Outbound</fullName>
            </value>
            <value>
                <fullName>De-escalation</fullName>
            </value>
            <value>
                <fullName>Email - Inbound</fullName>
            </value>
            <value>
                <fullName>Email - Outbound</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Knowledge Base Usage</fullName>
            </value>
            <value>
                <fullName>Next Steps</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Suspended-Awaiting Cust Action</fullName>
            </value>
            <value>
                <fullName>Update Request</fullName>
            </value>
            <value>
                <fullName>Transfer AE</fullName>
            </value>
            <value>
                <fullName>Transfer PC</fullName>
            </value>
            <value>
                <fullName>Transfer Combo</fullName>
            </value>
            <value>
                <fullName>Escalate - Internal- PCT</fullName>
            </value>
            <value>
                <fullName>Escalate - Client- PCT</fullName>
            </value>
            <value>
                <fullName>Call-Outbound-PCT</fullName>
            </value>
            <value>
                <fullName>Email-Outbound PCT</fullName>
            </value>
            <value>
                <fullName>Call-Inbound-PCT</fullName>
            </value>
            <value>
                <fullName>Email-Inbound PCT</fullName>
            </value>
            <value>
                <fullName>Translation</fullName>
            </value>
            <value>
                <fullName>iConnect</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Automated Follow-up email sent</fullName>
            </value>
            <value>
                <fullName>Issue not resolved</fullName>
            </value>
            <value>
                <fullName>Escalate - Internal</fullName>
            </value>
            <value>
                <fullName>Escalate - Tier2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_Up_Rule_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Rule_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Follow-Up Rule Configuration</label>
    <referenceTo>Follow_Up_Rule_Configuration__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Substatus__c.field-meta.xml
<CustomField>
    <fullName>Substatus__c</fullName>
    <label>Substatus</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Documents Required</fullName>
            </value>
            <value>
                <fullName>App Received - Missing Attest</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved, Subject To</fullName>
            </value>
            <value>
                <fullName>Approved - Sent to Pharmacy</fullName>
            </value>
            <value>
                <fullName>AR Created in error</fullName>
            </value>
            <value>
                <fullName>Attest Incomp App Miss Info</fullName>
            </value>
            <value>
                <fullName>Attest Not Rcvd App Miss Info</fullName>
            </value>
            <value>
                <fullName>Attest Received - Missing App</fullName>
            </value>
            <value>
                <fullName>Attest Sent - App Filed</fullName>
            </value>
            <value>
                <fullName>Attest with App Sent</fullName>
            </value>
            <value>
                <fullName>Awaiting 2nd Attempt</fullName>
            </value>
            <value>
                <fullName>Awaiting 3rd Attempt</fullName>
            </value>
            <value>
                <fullName>Awaiting 3rd Party Response</fullName>
            </value>
            <value>
                <fullName>Awaiting C3I Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Client response</fullName>
            </value>
            <value>
                <fullName>Awaiting Cognizant Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Covance Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Response</fullName>
            </value>
            <value>
                <fullName>Awaiting Deskside</fullName>
            </value>
            <value>
                <fullName>Awaiting Escalation</fullName>
            </value>
            <value>
                <fullName>Awaiting Exostar Action</fullName>
            </value>
            <value>
                <fullName>Awaiting info from requester</fullName>
            </value>
            <value>
                <fullName>Awaiting Internal Response</fullName>
            </value>
            <value>
                <fullName>Awaiting Medidata Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Oracle Action</fullName>
            </value>
            <value>
                <fullName>Awaiting PF Action</fullName>
            </value>
            <value>
                <fullName>Awaiting Project Completion</fullName>
            </value>
            <value>
                <fullName>Awaiting T1 Level 1 Action</fullName>
            </value>
            <value>
                <fullName>Response Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
            </value>
            <value>
                <fullName>Candidate</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>End Of Day</fullName>
            </value>
            <value>
                <fullName>Former Customer</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Marked For Deletion</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>New Customer</fullName>
            </value>
            <value>
                <fullName>Occasional</fullName>
            </value>
            <value>
                <fullName>Portfolio Manager</fullName>
            </value>
            <value>
                <fullName>Present Customer</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Short Term</fullName>
            </value>
            <value>
                <fullName>Signed Off</fullName>
            </value>
            <value>
                <fullName>Signed On</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Pending Active</fullName>
            </value>
            <value>
                <fullName>Inactive - Pending</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_Up_Rule_Configuration__c/Follow_Up_Rule_Configuration__c.object-meta.xml
<CustomObject>
    <label>Follow-Up Rule/CSAT Configuration</label>
    <nameField>
        <displayFormat>FUC-{0000}</displayFormat>
        <label>Follow-Up Rule/CSAT Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow-Up Rule/CSAT Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up_Rule_Configuration__c/fields/AR_Not_Resolved_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>AR_Not_Resolved_Email_Template__c</fullName>
    <label>AR Not Resolved Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Follow_Up_Rule_Configuration__c/fields/AU_FU_Comments_Recipient__c.field-meta.xml
<CustomField>
    <fullName>AU_FU_Comments_Recipient__c</fullName>
    <label>AU FU Comments Recipient</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Follow_Up_Rule_Configuration__c/fields/From_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Email_Address__c</fullName>
    <label>From Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AUF_Controller.cls
public class AUF_Controller 
{
    public case cs{get;set;}
    public Id taskId{get;set;}
    public string comments{get;set;}
    public boolean showForm{get;set;}
    
    public AUF_Controller()
    {
        showForm = true;
        Id caseId = ApexPages.currentPage().getParameters().get('id');
        taskId = ApexPages.currentPage().getParameters().get('taskId');
        if (caseId != null) {
            cs = [SELECT Id, CaseNumber, Resolution__c,Substatus__c,AccountId, Follow_Up_Rule_Configuration__r.From_Email_Address__c,
                    Follow_Up_Rule_Configuration__r.AU_FU_Comments_Recipient__c,Follow_Up_Rule_Configuration__r.AR_Not_Resolved_Email_Template__c 
                    FROM Case WHERE Id = :caseId LIMIT 1];
        } else {
            cs = new Case();
        }
    }
    
    public void submitresponse()
    {
        if (String.isNotBlank(comments)) { 
            try{
                Activities__c act = new Activities__c();
                act.Case__c = cs.Id;
                act.Description__c = comments;
                act.Activity_Source__c = 'Follow-up on Case';
                act.Status__c = 'Done';
                act.Type__c = 'Issue not resolved';
                act.Priority__c = '4-Low';
                act.Account__c = cs.AccountId;
                insert act;

                cs.Substatus__c = 'Response Received';
                update cs;
                showForm = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Response submitted successfully.'));
                
                sendEmailUsingTemplate(act.Id, cs);
            }catch(Exception e){
                system.debug(e.getMessage());
            }
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter comments before submitting.'));
        }
    }
    
    public static void sendEmailUsingTemplate(Id actId,Case c) {
        try {
            Contact tempContact = new Contact(
                LastName = 'TempRecipient',
                Email    = c.Follow_Up_Rule_Configuration__r.AU_FU_Comments_Recipient__c
            );
            insert tempContact;

            EmailTemplate emailtemp = [SELECT Id FROM EmailTemplate WHERE DeveloperName =:c.Follow_Up_Rule_Configuration__r.AR_Not_Resolved_Email_Template__c LIMIT 1];
            Id orgWideEmailId = [SELECT Id FROM OrgWideEmailAddress WHERE Address =: c.Follow_Up_Rule_Configuration__r.From_Email_Address__c LIMIT 1].Id;
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setTargetObjectId(tempContact.Id);
            email.setTemplateId(emailtemp.Id);
            email.setWhatId(actId);
            email.setOrgWideEmailAddressId(orgWideEmailId);

            // Ensure that the email is sent to the target object's email address
            email.setSaveAsActivity(false); // Optional: Don't log as an activity

            // Send the email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
            
            delete tempContact;
            System.debug('Email sent successfully.');
        } catch (Exception ex) {
            System.debug('Error sending email: ' + ex.getMessage());
        }
    }
}