force-app/main/default/objects/Contact_Sites__c/Contact_Sites__c.object-meta.xml
<CustomObject>
    <label>Contact Sites</label>
    <nameField>
        <displayFormat>SITE-{000}</displayFormat>
        <label>Contact Sites Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Sites__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Sites</relationshipLabel>
    <relationshipName>Contact_Sites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Sites__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Site__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contact Sites</relationshipLabel>
    <relationshipName>Contact_Sites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Studies__c/Contact_Studies__c.object-meta.xml
<CustomObject>
    <label>Contact Studies</label>
    <nameField>
        <displayFormat>STUDY-{000}</displayFormat>
        <label>Contact Studies Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Studies__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Studies</relationshipLabel>
    <relationshipName>Contact_Studies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Studies__c/fields/Study__c.field-meta.xml
<CustomField>
    <fullName>Study__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Study</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Study__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Study__c</referenceTo>
    <relationshipLabel>Contact Studies</relationshipLabel>
    <relationshipName>Contact_Studies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>Site</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study__c/Study__c.object-meta.xml
<CustomObject>
    <label>Study</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>Study</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study__c/fields/Study__c.field-meta.xml
<CustomField>
    <fullName>Study__c</fullName>
    <label>Study #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseHelperController.cls
public class CaseHelperController {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<Id>> getContactSiteStudyMap(Id contactId) {
        Map<String, List<Id>> result = new Map<String, List<Id>>();

        List<Id> siteIds = new List<Id>();
        List<Id> studyIds = new List<Id>();

        for (Contact_Sites__c cs : [
            SELECT Site__c FROM Contact_Sites__c WHERE Contact__c = :contactId AND Site__c != NULL
        ]) {
            siteIds.add(cs.Site__c);
        }

        for (Contact_Studies__c cs : [
            SELECT Study__c FROM Contact_Studies__c WHERE Contact__c = :contactId AND Study__c != NULL
        ]) {
            studyIds.add(cs.Study__c);
        }

        result.put('siteIds', siteIds);
        result.put('studyIds', studyIds);

        return result;
    }

    @AuraEnabled(cacheable=true)
    public static Map<Id, String> getSiteNames(List<Id> siteIds) {
        Map<Id, String> siteMap = new Map<Id, String>();
        for (Site__c s : [SELECT Id, Name FROM Site__c WHERE Id IN :siteIds]) {
            siteMap.put(s.Id, s.Name);
        }
        return siteMap;
    }

    @AuraEnabled(cacheable=true)
    public static Map<Id, String> getStudyNames(List<Id> studyIds) {
        Map<Id, String> studyMap = new Map<Id, String>();
        for (Study__c s : [SELECT Id, Name FROM Study__c WHERE Id IN :studyIds]) {
            studyMap.put(s.Id, s.Name);
        }
        return studyMap;
    }
}